* Bookworm Hut

Book reading tracker web application built in Clojure and ClojureScript.

** Goal

The idea of the project is to create a simple book reading tracker while improving my craftsmanship, expanding my knowledge and getting out of my comfort zone. To that end, I will work with a Lispy language emphasizing the functional programming paradigm. Two things that I didn't have the pleasure to try out during my professional career. At the same time, this will give me more insights into Lisp and maybe understand a better why some people like Paul Graham praise it.

** Dependencies

*TODO*: List dependencies and explain the installation steps to run the project

** Local Development

*** Frontend

#+begin_src bash
npx shadow-cljs watch app
#+end_src

*** Backend

#+begin_src bash
lein repl
#+end_src

Once the repl is initialized, we need to run

#+begin_src lisp
(start-server)
#+end_src

After that, we can reload the code after modifying it with

#+begin_src lisp
(use 'bookworm-hut-backend.core :reload)
#+end_src

*UNLESS* we modify the =start-server=
